require_relative '../all_class/genre'
require_relative '../all_class/music_albums'
require_relative '../all_class/game'
require_relative '../all_class/item'
require_relative '../all_class/book'
require_relative '../all_class/label'
require_relative '../all_class/author'
